name: solano_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
      # State Management
  flutter_bloc: ^8.1.6

  # Caching
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5

  # Networking
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1

  # Routing
  go_router: ^14.6.3

  # Localization
  easy_localization: ^3.0.7

  # Depedency Injection
  get_it: ^7.7.0

  # Json Parsing
  json_annotation: ^4.9.0

  # Utility
  fpdart: ^1.1.0
  logger: ^2.3.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  stream_transform: ^2.1.0

  # UI
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  cached_network_image: ^3.3.1
  build_runner: ^2.4.14
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.3
  auto_size_text: ^3.0.0
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0+3
  multiselect: ^0.1.1
  fluttertoast: ^8.2.12
  country_code_picker: ^3.2.0
  table_calendar: ^3.1.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_credit_card: ^4.0.1
  flutter_multi_formatter: ^2.13.0
  fl_chart: ^0.70.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  socket_io_client: ^3.0.2
  flutter_html: ^3.0.0


  flutter_inappwebview: ^6.1.5
  palette_generator: ^0.3.3+6
  solana_wallet_adapter: ^0.1.5
  url_launcher: ^6.3.1

dev_dependencies:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png" # Buraya ikonunun yolunu ekle
  adaptive_icon_background: "#ffffff" # Android için arka plan rengi (isteğe bağlı)
  adaptive_icon_foreground: "assets/launcher_icon.png" # Android için foreground ikon (isteğe bağlı)

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/